name: Maxima Build

on: [push, pull_request]
    
concurrency:
  group: ${{ github.workflow }}-${{ github.event.pull_request.number || github.ref }}
  cancel-in-progress: true

jobs:
  build:
    name: Maxima
    runs-on: ${{ matrix.os }}

    continue-on-error: ${{ matrix.experimental }}  
    strategy:
      fail-fast: false
      matrix:
        rust-version: [nightly]
        os: [ubuntu-latest-m, windows-latest-l]
        experimental: [false]

    env:
      CARGO_TERM_COLOR: always

    steps:
    - name: Checkout the repo
      uses: actions/checkout@v2

    - name: Cache Rust ${{ matrix.rust-version }}
      uses: actions/cache@v3
      with:
        path: ${{ github.workspace }}\rust\.rustup
        key: rust-${{ matrix.rust-version }}-${{ hashFiles('**/rust-toolchain') }}

    - name: Setup Rust ${{ matrix.rust-version }}
      uses: actions-rs/toolchain@v1
      with:
        profile: minimal
        toolchain: ${{ matrix.rust-version }}
        override: true
        components: rustfmt, clippy

    - name: Install Dependencies
      id: install-depends
      if: runner.os == 'Linux'
      run: |
        sudo apt-get install -y musl-tools
        rustup target add x86_64-unknown-linux-musl

    - uses: Swatinem/rust-cache@v2
      with:
        shared-key: ${{ runner.os}}-rust-deps
        cache-on-failure: true
        save-if: ${{ github.ref == 'refs/heads/master' }}

    - name: Cache OpenSSL
      id: cache-openssl
      if: runner.os == 'Windows'
      uses: actions/cache@v3
      with:
        path: |
          ${{ github.workspace }}\vcpkg\installed\x64-windows-static-md
        key: ${{ runner.os }}-vcpkg-openssl

    - name: Clone vcpkg and compile OpenSSL
      if: runner.os == 'Windows' && steps.cache-openssl.outputs.cache-hit != 'true'
      run: |
        git clone https://github.com/microsoft/vcpkg.git
        cd vcpkg
        [Environment]::SetEnvironmentVariable("VCPKG_DEFAULT_BINARY_CACHE", "${{ github.workspace }}/vcpkg/cache/", "User")
        .\bootstrap-vcpkg.bat
        .\vcpkg install openssl:x64-windows-static-md

    - name: Save OpenSSL Cache
      id: cache-openssl-save
      if: runner.os == 'Windows'
      uses: actions/cache/save@v3
      with:
        path: |
          ${{ github.workspace }}\vcpkg\installed\x64-windows-static-md
        key: ${{ runner.os }}-vcpkg-openssl

    - name: Build Maxima
      if: runner.os == 'Windows'
      run: |
        cargo build --release
      env:
        VCPKGRS_DYNAMIC: "0"
        OPENSSL_DIR: ${{ github.workspace }}\vcpkg\installed\x64-windows-static-md
        OPENSSL_STATIC: "1"

    - name: Build Maxima
      if: runner.os == 'Linux'
      run: |
        cargo build --release --target x86_64-unknown-linux-musl
      env:
        RUSTFLAGS: "-C target-feature=+crt-static"

    - uses: actions/upload-artifact@v3
      if: runner.os == 'Windows'
      with:
        name: maxima-x86_64-win64
        path: |
          target/release/maxima_native.dll
          target/release/maxima-service.exe
          target/release/maxima-bootstrap.exe
          target/release/maxima-cli.exe
          target/release/maxima.exe

    - name: List Files
      if: runner.os == 'Linux'
      run: |
        ls -l target/x86_64-unknown-linux-musl/release

    - uses: actions/upload-artifact@v3
      if: runner.os == 'Linux'
      with:
        name: maxima-x86_64-linux-musl
        path: |
          target/x86_64-unknown-linux-musl/release/libmaxima_native.so
          target/x86_64-unknown-linux-musl/release/maxima-bootstrap
          target/x86_64-unknown-linux-musl/release/maxima-cli
          target/x86_64-unknown-linux-musl/release/maxima
